---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for CentOS
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates for Ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers
