- name: create user
  tags: always
  ansible.builtin.user:
    name: simone
    groups: root

- name: add sudoers file for simone
  tags: always
  ansible.builtin.copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440

- name: add ssh key for simone user
  tags: always
  ansible.builtin.authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF8P+G5vuGY05eSOCHW67+NovdVec+JK6d159W4KWfnN ytanoue@CentOS"

- name: configure openssh based on template
  ansible.builtin.template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
